repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3
  hooks:
   - id: terraform_fmt
   - id: terraform_validate
- repo: git@github.com:plangrid/plangrid-commitlint.git
  rev: v1.0.1
  hooks:
    - id: plangrid-commitlint
      stages: [commit-msg]
      always_run: true
      pass_filenames: true
- repo: local
  hooks:
    - id: find-git-dependencies
      name: find-git-dependencies
      entry: bash -c "find . -name '*.tf' -not -path '*.terraform*' | sort -u | xargs grep -h 'git::'  | tr -d ' ' | tr -d '\"' | sort -n | uniq | awk -F '::' '{print $2}' > dependencies.txt"
      language: system
      pass_filenames: false
